"""empty message

Revision ID: 1d8be5a74745
Revises: 8ef6e79ff170
Create Date: 2018-05-04 09:17:49.649973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8be5a74745'
down_revision = '8ef6e79ff170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('end', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_events_end'), 'events', ['end'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_end'), table_name='events')
    op.drop_column('events', 'end')
    # ### end Alembic commands ###
