"""empty message

Revision ID: 26f9564ecc5f
Revises: b44f4f1dbf78
Create Date: 2018-05-10 11:19:21.462348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f9564ecc5f'
down_revision = 'b44f4f1dbf78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classname', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'eventclass', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'class_id')
    op.drop_table('eventclass')
    # ### end Alembic commands ###
