"""empty message

Revision ID: 69bb52e8c118
Revises: 6614381584db
Create Date: 2018-05-03 23:32:11.285097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69bb52e8c118'
down_revision = '6614381584db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User_event_details', 'timestamp')
    op.add_column('event_details', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_details', 'timestamp')
    op.add_column('User_event_details', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
