"""empty message

Revision ID: 8ef6e79ff170
Revises: 9d72b715b6e3
Create Date: 2018-05-04 00:18:38.167177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ef6e79ff170'
down_revision = '9d72b715b6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('details')
    op.add_column('event_details', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_details', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_details', type_='foreignkey')
    op.drop_column('event_details', 'user_id')
    op.create_table('details',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('detail_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['detail_id'], ['event_details.id'], name='details_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='details_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
