"""empty message

Revision ID: 9d72b715b6e3
Revises: 69bb52e8c118
Create Date: 2018-05-03 23:44:56.259279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d72b715b6e3'
down_revision = '69bb52e8c118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('details',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('detail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['detail_id'], ['event_details.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('User_event_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_event_details',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='User_event_details_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='User_event_details_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'event_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('details')
    # ### end Alembic commands ###
