"""empty message

Revision ID: b44f4f1dbf78
Revises: 5fc2d8394e38
Create Date: 2018-05-04 11:08:40.768406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44f4f1dbf78'
down_revision = '5fc2d8394e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('link', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'link')
    # ### end Alembic commands ###
