"""empty message

Revision ID: ee64b8c4ba35
Revises: 1d8be5a74745
Create Date: 2018-05-04 09:51:51.198001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee64b8c4ba35'
down_revision = '1d8be5a74745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.drop_column('events', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.drop_column('events', 'start_time')
    op.drop_column('events', 'end_time')
    # ### end Alembic commands ###
